### ISSUE TITLE
Useskill command enhancement proposal

### ISSUE THREAD

**Issue by Wibblepuppy** [gwdevhub/GWToolboxpp#1248]
**Problem:** Using command /useskill \<skill> to auto-activate Fire Attunement results in the character stopping to recast more frequently than necessary while up to half the duration of the enchantment remains. This is due to the significant difference between recharge time (30 seconds) and effect duration (variable with attribute level but say 62 seconds).

**Proposed Solution:** Introduce an optional parameter to /useskill command that dictates a timer before forcing reuse. Format could be /useskill \<skill> [seconds]. Used with only parameter \<skill> the default conditions apply, otherwise respond to \<skill> and [seconds]. 

**Intended Outcome:** Ensures closer synchronisation of recharge time and effect duration for skills that require stop-and-cast.

**Comment by 3vcloud** [comment]
Thanks for the detailed issue and the use case. This feature is pretty borderline automation, and it’s only still in the tool because at the time it was used in key areas like dhuum to spam dhuums rest, so any take on automating it further isn’t on the card unless there’s a really significant reason to automate gameplay like this.

I would argue that maintaining enchantments depending on in game factors such as HCT and HSR or other things that are happening at the time are one of the things that make this game both unique and challenging compared to other games, and to automate that logic and process even with a basic second timer would take away from that. 

Unless you’re automating gameplay for the sake of not wanting to engage with the content, this feature would be useless. If that is the case, toolbox isn’t meant to play the game for you, and despite current features giving cause to argue this point, we’re not going to make new features that do this.
