### ISSUE TITLE
Check in-game timestamp setting when loading to avoid overriding gw setting

### ISSUE THREAD

**Issue by Demne** [gwdevhub/GWToolboxpp#1285]
Hello,

With version 6.25, as soon as i open TB++ the option: Options [F11] -> General -> Show chat timestamps is automatically disabled.

**Comment by callmepsywolf** [comment]
Depends on which should be the leading system I guess. If GW should be the leading system on initial load then
`GW::Chat::ToggleTimestamps(show_timestamps);` should be removed. Otherwise it seems like it's working as intended. Set the option for Show chat timestamps in the "Chat Settings" Module and it shouldn't turn off again on initial load as it should be saved when leaving TB. 

ChatSettings.cpp
```
void ChatSettings::LoadSettings(ToolboxIni* ini)
{
    ToolboxModule::LoadSettings(ini);

    LOAD_BOOL(show_timestamps);
    LOAD_BOOL(show_timestamp_24h);
    LOAD_BOOL(show_timestamp_seconds);
    LOAD_BOOL(hide_player_speech_bubbles);
    LOAD_BOOL(npc_speech_bubbles_as_chat);
    LOAD_BOOL(redirect_npc_messages_to_emote_chat);
    LOAD_BOOL(redirect_outgoing_whisper_to_whisper_channel);
    LOAD_BOOL(openlinks);
    LOAD_BOOL(auto_url);

    timestamps_color = Colors::Load(ini, Name(), VAR_NAME(timestamps_color), Colors::RGB(0xc0, 0xc0, 0xbf));
    GW::UI::SetOpenLinks(openlinks);
    GW::Chat::ToggleTimestamps(show_timestamps);
    GW::Chat::SetTimestampsColor(timestamps_color);
    GW::Chat::SetTimestampsFormat(show_timestamp_24h, show_timestamp_seconds);
}
```
