### ISSUE TITLE
Let "Reapply appropriate title" take closest enemy into account

### ISSUE THREAD

**Issue by HiImFlo** [gwdevhub/GWToolboxpp#427]
This hotkey currently reapplies a title based upon just the map ID. LB usually doesnt conflict with anything except some super niche quests, but for the eotn titles you will quite often want a different title than the map would suggest. For example dwarven title when fighting destroyers in an asura area.

Therefore, check the closest enemy. If its a destroyer, apply dwarven title, if its a charr, apply ebon vanguard title, and if its neither just go with the old map-ID based logic.

**Comment by 3vcloud** [comment]
Have you got specific examples for this? Maybe it just needs to consider the current mission instead?

**Comment by HiImFlo** [comment]
Just from the top of my head, i am sure there is more:
Assault on the stronghold, charr invaders, leader of the pack, vision of the raven spirit

**Comment by 3vcloud** [comment]
Mission maps like Assault are already catered for, and I think any quests aren't worth adding this logic in for - for these one-off exceptions you can just apply the title yourself

**Comment by 3vcloud** [comment]
Closing this for now, but if there are any missions or maps where the wrong title is applied then lmk

**Comment by PostCrafter** [comment]
I think you misunderstood his intention, he wanted to equip the appropriate title based on enemies surrounding him (maybe use the target for simplicity). In Assault on the Stronghold you're fighting both Charr and Destroyer, so hitting a hotkey to equip the appropriate title depending on enemies would be quite nice.
This could be implemented fairly easy if we had the ModelIDs of all Charr and Destroyers (not sure if Lightbringer Title is relevant anywhere EotN titles are relevant), so we can apply the correct title in these cases and default to current behaviour otherwise.

**Comment by 3vcloud** [comment]
`/targettitle` could be cool I guess, but its a lot of hassle to check through model IDs for this 1 feature that will only really be used in these few cases, which is why I closed it. Theres argument for it regardless so I'll reopen
