### ISSUE TITLE
hide people from friends list

### ISSUE THREAD

**Issue by ghost** [gwdevhub/GWToolboxpp#532]
Well, I have a bug in my gw account... there is someone I can't delete from my in-game friends list (I think that I added him for a trade or something). 
It will be nice to have an option in tb friends list to hide specific people

**Comment by DubbleClick** [comment]
Oh god this would actually be so nice.

**Comment by 3vcloud** [comment]
Not going to tackle this because a) wouldn't be a proper fix for the issue, just hiding the problem away and b) we've got better contact with the game devs now so I'll bring it to their attention - to do this though it would be good to have a few examples of players who cant remove someone from their friends list
