### ISSUE TITLE
reroll confirmation

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [gwdevhub/GWToolboxpp#775]
When I'm in an explorable area and use the /rr command, I don't want a confirmation window. Maybe this should be optional, or only apply when you're in a party with other players or something?

**Comment by 3vcloud** [comment]
press your return key

**Comment by 3vcloud** [comment]
Scratch that, return doesn't work for this confirmation dialog

**Comment by 3vcloud** [comment]
its a bit hacky - because you could still have the enter key pressed as a result of sending `/rr derv` it could see that "oh enter is currently pressed, that means OK"

As a dirty workaround I put a 500ms delay on checking, so its not as responsive as the in-game F12 -> C -> Enter that you would normally use

**Comment by DubbleClick** [comment]
We can use the imgui method to find out if it's a new enter press.
