### ISSUE TITLE
[Hotkeys]: Level 1 Character Hotkey to Xunlai Chest

### ISSUE THREAD

**Issue by ChandlerFerry** [gwdevhub/GWToolboxpp#961]
0. Create hotkey to Xunlai chest on Numpad 0, blocked from sending to Guildwars
1. Create Factions Character
2. Enter Guild Hall
3. Press Hotkey (Nothing Occurs)
4. Leave Guild Hall
5. Enter Town (become level 2)
6. Press Hotkey (Works as intended)

**Comment by ChandlerFerry** [comment]
Even if you purchase the storage, it still does not function.

Just did a quick debug of the problem, is tied to the `Trigger hotkey when playing on PvP character` checkbox.

In Toolbox, a level 1 character is currently considered a PvP character.

**Comment by adituv** [comment]
Found the cause: the pvp character detection is actually done by whether any of the first major cities are unlocked, which they aren't for a pve character during tutorial in factions or NF.  Even for NF, it's incorrect because it checks for Kamadan instead of Chahbek.

https://github.com/HasKha/GWToolboxpp/blob/5795541881683d6e73ab24d315e5cfa9013de768/GWToolboxdll/Windows/HotkeysWindow.cpp#L82

**Comment by 3vcloud** [comment]
Rather than tweaking this line for chahbek and making a pr, if rather someone take the comment I made into account and check the code to see if we can properly detect the pvp status of a character

**Comment by adituv** [comment]
https://github.com/GregLando113/GWCA/blob/9a51bfcf2d888a901f40f1c4240a8659de5e6791/Include/GWCA/GameEntities/Player.h#L24
