### ISSUE TITLE
[Hotkey - Guild Wars Key] Cannot trigger hotkey on map load

### ISSUE THREAD

**Issue by HiImFlo** [gwdevhub/GWToolboxpp#973]
When creating a hotkey that triggers a Guild Wars Key, there is no setting to trigger it on mapload, but this setting exists for most/all other hotkey types

![grafik](https://github.com/gwdevhub/GWToolboxpp/assets/37843152/67a20a90-1eaa-4341-9dff-0b27f95ec663)

**Comment by 3vcloud** [comment]
This is deliberate - most guild wars keys are only valid once their related ui component is loaded on screen - this doesn’t happen immediately, and without hooking for every relevant ui component it isn’t feasible to add as a feature either

**Comment by HiImFlo** [comment]
I think the usecase to let a hero bond you on map load is somewhat common - is there a way to do this without GW Keys that I dont see? If no, would it be possible to create a "toolbox version" of the "Order Hero to use skill" GW Key?

**Comment by DubbleClick** [comment]
Not without first waiting for the hero flags (compass) to be rendered first, which brings us back to why it's not possible to trigger it on map load in the first place.

**Comment by 3vcloud** [comment]
Thats actually a different ui component (hero skill bars), but the concept is the same; every action in the game is actually registered by separate "modules" on map load - even in-game keys. This is done asynchronously because resources for these modules need to be loaded from the gw dat for things like ui components, so we can't reliably say when a component is ready and listening for a keypress without more hooks being written and maintained.

Having said that, you could instead go to the effort of having to remember to press the key yourself and not worry about it automating your gameplay even further.
