### ISSUE TITLE
Make the "Renderer:" label at bottom of GW graphics tab useful

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GWToolboxpp#976]
At the moment, it'll either say "DirectX 8.0" or "DirectX 9.0" based on a simple run time flag; we could hook this call to instead somehow query the graphics driver being used in some way, and make a more informed decision for:

 - DirectX 9
 - DirectX 12
 - DXVK

**Comment by BearsMan** [comment]
We know that Guild Wars uses DirectX 9 for the renderer, and there haven't been updates to the DirectX renderer since the game's launch. I know a plugin for Guild Wars converts DirectX to DirectX12. I could post the GitHub link if you want to have a look. I think DirectX 12 would be more accurate to use in terms of how the game engine uses whatever GPU the user has.

<img width="63" alt="image" src="https://github.com/gwdevhub/GWToolboxpp/assets/34116754/2d54e4f4-8af9-4bb4-9785-db6def282e5a">
